node1: ./extent-node --listenUrl 127.0.0.1:4001 --dirs store1/sda --dirs store1/sdb --ID 1
node2: ./extent-node --listenUrl 127.0.0.1:4002 --dirs store2/sda --dirs store2/sdb --ID 2
node3: ./extent-node --listenUrl 127.0.0.1:4003 --dirs store3/sda --dirs store3/sdb --ID 3
