version: '3'

services:
  partition-server:
     depends_on: 
        - extent-node
        - stream-manager
     image: journeymidnight/autumn:latest
     command: ./autumn-ps 
        --nosync 
        --advertise-listen 127.0.0.1:9955 
        --listen :9955 
        --psid 12 
        --sm-urls stream-manager:3401 
        --etcd-urls stream-manager:2379
        --max-extent-size 64
        --skiplist-size 16
     ports:
       - "9955:9955" 
  stream-manager:
     image: journeymidnight/autumn:latest
     command: 
       ./autumn-manager 
       --dir sm1.db 
       --name sm1
       --listen-client-urls http://0.0.0.0:2379 
       --advertise-client-urls http://0.0.0.0:2379 
       --listen-peer-urls http://0.0.0.0:12380  
       --advertise-peer-urls http://127.0.0.1:12380 
       --initial-cluster-token sm-cluster-1 
       --initial-cluster 'sm1=http://127.0.0.1:12380' 
       --initial-cluster-state new 
       --listen-grpc 0.0.0.0:3401
     ports:
       - "2379:2379" 
       - "3401:3401"
  extent-node:
     image: journeymidnight/autumn:latest
     depends_on: 
       - stream-manager
     command: sh node_run.sh 
